name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run tests
        run: make test
        working-directory: ./2021

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./2021/coverage.out
          verbose: true
