name: CI
on: [push, pull_request]

jobs:
  test-2020:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        working-directory: ./2020
        with:
          toolchain: stable
        run:
          - ./test.sh

  test-2021:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run tests
        run: make test
        working-directory: ./2021

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./2021/coverage.out
          verbose: true
  test-2022:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch .
        working-directory: ./2022

      - name: Run tests
        run: hatch run codecov
        working-directory: ./2022

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./2022/coverage.xml
          verbose: true
